# Generated by Django 4.1.5 on 2024-01-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(db_column='customer', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer'),
        ),
    ]
