# Generated by Django 4.1.5 on 2024-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='tax_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax_percentage',
            field=models.FloatField(default=0, null=True),
        ),
    ]
