# Generated by Django 4.1.5 on 2024-01-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_tax_amount_alter_sale_tax_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_percentage',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('hold', 'Hold'), ('partial_paid', 'Partial Paid')], default='paid', max_length=20),
        ),
    ]
