# Generated by Django 4.1.5 on 2024-01-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_sale_tax_amount_remove_sale_tax_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sub_total',
        ),
    ]
