# Generated by Django 4.1.5 on 2024-01-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_sub_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saledetail',
            old_name='price',
            new_name='sell_price',
        ),
    ]
