# Generated by Django 4.1.5 on 2024-01-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_price_saledetail_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
    ]
